name: Docs

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: nbdev docs
        uses: fastai/workflows/quarto-ghp@master
